[book]
authors = ["madan maholvi"]
language = "en"
src = "src"
title = "महोलवी नामा "
description = "The life and works of Madan Maholvi"

[preprocessor.katex]

[output.html]
theme = "theme"
additional-css = ["css/custom.css"]
cname = "maholvi.shutri.com"
no-section-label = true

[output.html.print]
enable = false
